# .pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    # Run the Ruff formatter.
    -   id: ruff-format
        types_or: [python, pyi, jupyter]
    # Run the Ruff linter, with auto-fix enabled.
    -   id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    -   id: mypy
        # This ensures mypy can see all installed packages
        additional_dependencies:
            - "langchain"
            - "langgraph"
            - "typer"
            - "fastapi"
            - "pydantic"
